### ISSUE TITLE
AttributeError: 'XMLSchema10' object has no attribute 'local_name' when xs:elements > 1

### ISSUE THREAD

**Issue by garcia556** [cre-dev/xml2db#11]
Hello,

when loading schema with more than 1 xs:emenent it throws error:

```
Traceback (most recent call last):
  File "/home/dmitryg/kd_dev/_research/xml2db/main.py", line 4, in <module>
    data_model = DataModel(
                 ^^^^^^^^^^
  File "/home/dmitryg/kd_dev/_research/xml2db/venv/lib/python3.11/site-packages/xml2db/model.py", line 134, in __init__
    self._build_model()
  File "/home/dmitryg/kd_dev/_research/xml2db/venv/lib/python3.11/site-packages/xml2db/model.py", line 226, in _build_model
    root_table = self._parse_tree(
                 ^^^^^^^^^^^^^^^^^
  File "/home/dmitryg/kd_dev/_research/xml2db/venv/lib/python3.11/site-packages/xml2db/model.py", line 300, in _parse_tree
    parent_type = parent_node.local_name
                  ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'XMLSchema10' object has no attribute 'local_name'
```

Python 3.11, the issue is easily reproduced with [junit-10](https://github.com/cre-dev/xml2db/blob/main/tests/sample_models/junit10/junit-10.xsd) schema.

[Orders](https://github.com/cre-dev/xml2db/blob/main/tests/sample_models/orders/orders.xsd) does work since there is only one xs:element inside.

Any clues how to resolve this?

Thank you.

**Comment by martinv13** [comment]
Hi,

Actually it is supposed to work with the junit10 schema at it is part of the test cases that you can run with pytest.

Maybe having multiple root elements is not the only reason that make it fail for you? The package is far from covering the whole XSD specification; it is well possible that it does not work with some schemas. Could you provide your schema or a simplified version of it?

If it does fail with the junit10 schema in your tests, could you provide some code to reproduce?

Thanks.

**Comment by garcia556** [comment]
Looks like another issue in my schema. No issues so far.
